<?php

namespace Jefferson49\Webtrees\Module\OAuth2Client;

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use League\OAuth2\Client\Token\AccessTokenInterface;

use function e;

/**
 * @var string			       $title
 * @var AccessTokenInterface   $access_token
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), e($title)]]) ?>

<h1><?=e($title) ?></h1>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
		<?= I18N::translate('Access Token Data') ?>
</div>

<label class="col-sm-3 col-form-label wt-page-options-label">
			<?= I18N::translate('Access Token: ') ?>
		</label>
</div>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($accessToken->getToken()) ?></span>
	</div>
</div>

<label class="col-sm-3 col-form-label wt-page-options-label">
			<?= I18N::translate('Refresh Token: ') ?>
		</label>
</div>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($accessToken->getRefreshToken()) ?></span>
	</div>
</div>

<label class="col-sm-3 col-form-label wt-page-options-label">
			<?= I18N::translate('Expired in: ') ?>
		</label>
</div>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($accessToken->getExpires()) ?></span>
	</div>
</div>

<label class="col-sm-3 col-form-label wt-page-options-label">
			<?= I18N::translate('Already expired? ') ?>
		</label>
</div>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= $accessToken->hasExpired() ? 'expired' : 'not expired' ?></span>
	</div>
</div>
