<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\HomePage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Jefferson49\Webtrees\Module\OAuth2Client\Factories\AuthorizationProviderFactory;
use Jefferson49\Webtrees\Module\OAuth2Client\LoginWithAuthorizationProviderAction;


/**
 * @var Tree|null $tree
 * @var string    $url
 */

$url = $url ?? route(HomePage::class);
$sign_in_button_labels = AuthorizationProviderFactory::getSignInButtonLables();

?>

<?php if (sizeof($sign_in_button_labels) > 0) : ?>
    <div class="wt-page-options wt-page-options-login">
        <div class="row mb-3">
            <label class="col-sm-3 col-form-label wt-page-options-label">
                <?= I18N::translate('Sign in with authorization provider') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <form method="post">
                    <?php foreach ($sign_in_button_labels as $provider_name => $sign_in_button_label) : ?>

                        <a href="<?= e(route(LoginWithAuthorizationProviderAction::class, [
                                'tree'          => $tree instanceof Tree ? $tree->name() : null,
                                'url'           => $url,
                                'provider_name' => $provider_name,
                            ])) ?>" type="submit" class="btn btn-secondary">
                            <?= $sign_in_button_label ?>
                        </a>
                    <?php endforeach ?>
                    <?= csrf_field() ?>
                </form>
            </div>
        </div>
    </div>
<?php endif ?>
