<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\OAuth2Client;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Jefferson49\Webtrees\Module\OAuth2Client\LoginWithAuthorizationProviderAction;

/**
 * @var Tree|null $tree
 */

$provider_names = AuthorizationProviderFactory::getAuthorizatonProviderNames();

?>

<?php if (sizeof($provider_names) > 0) : ?>
    <div class="row mb-3">
        <label class="col-sm-3 col-form-label wt-page-options-label">
            <?= I18N::translate('Sign in with authorization provider') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?php foreach ($provider_names as $provider_name) : ?>
                <form method="post" class="wt-page-options wt-page-options-login" action="<?= e(route(LoginWithAuthorizationProviderAction::class, [
                        'tree'          => $tree instanceof Tree ? $tree->name() : null,
                        "provider_name" =>  $provider_name,
                    ])) ?>" >
                    <button class="btn btn-secondary" type="submit">
                        <?= $provider_name ?>
                    </button>
                    <?= view('icons/spacer') ?>

                    <?= csrf_field() ?>
                </form>
            <?php endforeach ?>
        </div>
    </div>        
<?php endif ?>
