<?php

declare(strict_types=1);

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Jefferson49\Webtrees\Module\OAuth2Client\LoginWithAuthorizationProviderAction;
use Jefferson49\Webtrees\Module\OAuth2Client\OAuth2Client;

/**
 * @var string $title
 * @var string $base_url
 * @var bool   $show_webtrees_in_login_menu
 * @var bool   $dont_show_webtrees_login_menu
 */

$uses_https = strpos(Strtoupper($base_url), 'HTTPS://') === false ? false : true;

$redirect_url = route(LoginWithAuthorizationProviderAction::class);

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), e($title)]]) ?>

<h1><?=e($title) ?></h1>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<?php if (!$uses_https) : ?>
    <div class="alert alert-danger">
        <p><?= I18N::translate('Currently, webtrees does not use the HTTPS protocol. If signing in with authorization providers, it is urgently recommended to use HTTPS in order to encrypt the communication with the authorization provider. If your server supports the protocol, HTTPS can be activated by changing "base_url" in the webtrees "config.ini.php" file. Currently, "base_url" does not start with "https://".') ?></p>
    </div>
<?php endif ?>

<div class="h4">Redirect URL</div>
<div class="row mb-3">
    <label class="col-sm-3 col-form-label wt-page-options-label" for="redirect_url">Redirect URL</label>
    <div class="col-sm-9 wt-page-options-value">
        <input type="text" class="form-control" id="redirect_url-name" name="redirect_url" value="<?= e($redirect_url) ?>" dir="auto" required="required" disabled >
    </div>		
</div>

<form method="post" id="settings-form">
	<?= csrf_field() ?>
	<input type="hidden" name="save" id="save" value="1">
  
	<div class="h4">
		<?= I18N::translate('Settings for Sign In Menus') ?>	
	</div>

	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Show menu item for webtrees in sign in menu') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/checkbox', ['label' => MoreI18N::xlate('Show'), 'name' => OAuth2Client::PREF_SHOW_WEBTREES_IN_LOGIN_MENU, 'checked' => $show_webtrees_in_login_menu]) ?>
				<div class="form-text">
					<?= I18N::translate('By selecting/unselecting this option, it is possible to activate/deactivate the sign in menu entry for webtrees. If deactivated, only sign in menu entries for authorization providers might be shown.'); ?>
				</div>
			</div>
		</div>
	</fieldset>

	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Hide the webtrees sign in menu') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/checkbox', ['label' => I18N::translate('Hide'), 'name' => OAuth2Client::PREF_DONT_SHOW_WEBTREES_LOGIN_MENU, 'checked' => $dont_show_webtrees_login_menu]) ?>
				<div class="form-text">
					<?= I18N::translate('By selecting this option, it is possible to hide the original webtrees sign in menu. This might be helpful if the custom module specific top menu for sign in is used instead.'); ?>
				</div>
			</div>
		</div>
	</fieldset>

	<?php if (!$show_webtrees_in_login_menu && $dont_show_webtrees_login_menu) : ?>
		<div class="alert alert-warning">
			<p><?= I18N::translate('Currently, all menus to directly sign in with webtrees are deactivated. Therefore, only sign in with authorization providers is possible. Please be sure that you establish a webtrees administrator account with an authorization provider. Otherwise, administrator sign in is not possible any more. Hint: You can still access the original webtrees login page by typing the login route into the browser line, e.g.: http://my_site.net/webtrees/login/') ?></p>
		</div>
	<?php endif ?>	

    <div class="row mb-3">
		<div class="col">
			<p></p>
			<button type="submit" class="btn btn-primary">
				<?= view('icons/save') ?>
				<?= MoreI18N::xlate('save') ?>
			</button>
		</div>		
	</div>

</form>	

<?php View::push('javascript') ?>
<script>
    $('#select-all-1').change(function(e) {
        if (e.currentTarget.checked) {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', true);
        } else {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', false);
        }
    });
</script>
<?php View::endpush() ?>