<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Jefferson49\Webtrees\Module\OAuth2Client\LoginWithAuthorizationProviderAction;

/**
 * @var string $title
 * @var string $base_url
 * 
 */

$uses_https = strpos(Strtoupper($base_url), 'HTTPS://') === false ? false : true;

$redirect_url = route(LoginWithAuthorizationProviderAction::class);

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), e($title)]]) ?>

<h1><?=e($title) ?></h1>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<form method="post" id="settings-form">
	<?= csrf_field() ?>
	<input type="hidden" name="save" id="save" value="1">
  
    <?php if (!$uses_https) : ?>
        <div class="alert alert-danger">
            <p><?= I18N::translate('Currently, webtrees does not use the HTTPS protocol. If signing in with authorization providers, it is urgently recommended to use HTTPS in order to encrypt the communication with the authorization provider. If your server supports the protocol, HTTPS can be activated by changing "base_url" in the webtrees "config.ini.php" file. Currently, "base_url" does not start with "https://".') ?></p>
        </div>
    <?php endif ?>	    
</form>	

<div class="h4">Redirect URL</div>
<div class="row mb-3">
    <label class="col-sm-3 col-form-label wt-page-options-label" for="redirect_url">Redirect URL</label>
    <div class="col-sm-9 wt-page-options-value">
        <input type="text" class="form-control" id="redirect_url-name" name="redirect_url" value="<?= e($redirect_url) ?>" dir="auto" required="required" disabled >
    </div>		
</div>

<?php View::push('javascript') ?>
<script>
    $('#select-all-1').change(function(e) {
        if (e.currentTarget.checked) {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', true);
        } else {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', false);
        }
    });
</script>
<?php View::endpush() ?>