<?php

namespace Jefferson49\Webtrees\Module\OAuth2Client;

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

use function e;

/**
 * @var  string		$title
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), e($title)]]) ?>

<h1><?=e($title) ?></h1>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<form method="post" id="settings-form">
	<?= csrf_field() ?>
	<input type="hidden" name="save" id="save" value="1">

	<div class="h4">
		<?= I18N::translate('Settings') ?>	
	</div>

	<div class="row mb-3">
		<div class="col">
			<button type="submit" class="btn btn-primary">
				<?= view('icons/save') ?>
				<?= MoreI18N::xlate('Submit') ?>
			</button>
		</div>		
	</div>		
</form>	

<?php View::push('javascript') ?>
<script>
    $('#select-all-1').change(function(e) {
        if (e.currentTarget.checked) {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', true);
        } else {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', false);
        }
    });
</script>
<?php View::endpush() ?>